<!--
    Estilos Css => Carpeta Css => balk_linea_porducto_vista.css ,
                                  balk_estilos_generales.css
    *** Cuando se selecciona una linea de producto se carga esta vista con sus productos
     y descripciones ****
   -->
   <div class="cont-pagina"><!-- Cont = Principal -->
     <div class="row">

       <!-- /// Section = Info-Productos /// -->

       <div class="row"><!-- Barra linea productos -->

        <!-- =========( Menu = Lineas )========= -->
        <div class="col-lg-3 col-md-3 col-sm-3">
          <div class="cont-barra-left"><!-- Contenedor -->
           <div class="panel-group" id="accordion"><!--Contenido de los paneles -->

            <?php
            $i= 1;

            foreach ($this->Categorias as $Categorias)
            {
              $nomcategoria = trim($Categorias['nomcategoria']);
              $idcategoria  = $Categorias['idcategoria'];
              $id           = 'categoria'.$idcategoria;
              ?>
              <div class="panel"><!--Panel -->
               <div class="panel-heading cabezera-panel">
                 <h4 class="panel-title">
                  <a class="titulos_panel" data-id="<?=$id ;?>"  href="/#<?=$id ;?>"
                    data-toggle ="collapse"
                    data-parent ="#accordion"
                    idcategoria = <?=$idcategoria ;?> >

                    <?= $nomcategoria ;?>
                  </a><!-- titulo -->
                </h4>
              </div>
              <?php if ($i==1) :;?>
                <div id="<?=$id ;?>" class="panel-collapse collapse"><!-- Cuerpo del panel in-->
                <?php else :;?>
                  <div id="<?=$id ;?>" class="panel-collapse collapse"><!--  Cuerpo del panel -->
                  <?php endif;?>

                  <div class="panel-body" id="cuerpo_categorias-linea">
                   <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                     <?php foreach ($this->SubCategorias as $SubCategorias)
                     {
                        $nomsubcategoria     =  $SubCategorias['nomsubcategoria'];
                        $idcategoria_detalle = $SubCategorias['idcategoria'];
                        $idsubcategoria      = $SubCategorias['idsubcategoria'];
                      if ( $idcategoria == $idcategoria_detalle){
                        ?>
                        <li><a class="list-productos"
                        idsubcategoria  = <?= $idsubcategoria ;?>
                        idcategoria     = <?=$idcategoria ;?>
                        nomsubcategoria = <?="'".$nomsubcategoria."'"  ;?>
                        href="#"><?=$nomsubcategoria ;?> </a></li>
                        <?php }} ;?>
                      </ul><!--Menu accordion -->
                    </div>
                  </div>
                </div><!--Panel -->
                <?php $i++; } ;?>
              </div><!--Contenido de los paneles -->
            </div><!-- Contenedor -->
          </div>
          <!-- =========( Menu = Lineas )========= -->

          <!-- =========( Parte de Los Productos )========= -->
          <div class="contenido_interno">
           <div class="col-lg-9 col-md-9 col-sm-9">
             <div><!-- Contenedor -->
              <div class="col-lg-12 col-md-12 col-sm-12">

                  <div><!-- IMG = Linea Seleccionada -->
                    <img src="<?= BASE_IMG_LINEA_SELEC.$this->Imagen_Cabecera  ;?>" class="img-responsive img-linea-seleccionada">
                  </div><!-- IMG = Linea Seleccionada -->
              </div>

            <div class="contenido-descripcion">
              <div><!-- Titulo -->
                   <h4 class="titulo_linea_seleccionada"><?=$this->Texto_SubCategoria?></h4>
              </div><!-- Titulo -->

              <div class="col-lg-12 col-md-12 col-sm-12">
                  <div class="cont-presentacion-productos">
                      <!-- ======( Fila De Productos )====== -->
                        <div class="row">

                            <?php
                            foreach ($this->Productos as $Producto)  {
                              $nomproducto = $Producto['nomproducto'];
                              $idproducto  = $Producto['idproducto'];
                              ?>
                              <div class="col-lg-6 col-md-6 col-sm-6">
                               <div class="producto"  id="<?= $nomproducto ;?>" >
                                <?= $nomproducto ;?>
                              </div>
                            </div>
                            <?php } ;?>

                        </div>
                      <!-- ======( Fila De Productos )====== -->
                  </div>
              </div>
              </div>


            </div><!-- Contenedor -->
          </div>
        </div>

        <!-- =========( Parte de Los Productos )========= -->
      </div>
    </div>
  </div><!-- Cont = Principal -->
  <br />
  <br />
    <br />
  <br />
