<!--
    Js          => Carpeta Js  => balk_velocidad_slider.js
    Estilos Css => Carpeta Css => balk_linea_porducto_vista.css , balk_estilos_generales.css
    *** Cuando se selecciona una linea de producto se carga esta vista con sus productos
     y descripciones ****
-->
<div class="cont-pagina"><!-- Cont = Principal -->
	  <div class="row">

   <!-- /// Section = Info-Productos /// -->

   <div class=" row"><!-- Barra linea productos -->
     <div class=" col-lg-3 col-md-3 col-sm-3">
      <div class="cont-barra-left"><!-- Contenedor -->
       <div class="panel-group" id="accordion"><!--Contenido de los paneles -->

         <div class="panel"><!--Panel -->
           <div class="panel-heading cabezera-panel">
             <h4 class="panel-title">
                <a class="titulos_panel" href="#categorias" data-toggle="collapse"   data-parent="#accordion">ALIMENTARIA</a><!-- titulo -->
             </h4>
           </div>

           <div id="categorias" class="panel-collapse collapse in"><!-- Cuerpo del panel -->
             <div class="panel-body">

               <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                  <li><a class="list-productos" href="#">Desinfectantes. </a></li>
                  <li><a class="list-productos" href="#">Detergentes + Desinfectantes. </a></li>
                  <li><a class="list-productos" href="#">Detergentes Biodegradables. </a></li>
                  <li><a class="list-productos" href="#">Limpiadores especializados </a></li>
               </ul><!--Menu accordion -->

             </div>
           </div>
         </div><!--Panel -->

    <!-- /// Artes Graficas /// -->

         <div class="panel"><!--Panel -->

           <div class="panel-heading cabezera-panel">
             <h4 class="panel-title">
                <a class="titulos_panel" href="#artes_graficas" data-toggle="collapse"   data-parent="#accordion">ARTES GRÁFICAS</a><!-- titulo -->
             </h4>
           </div>

           <div id="artes_graficas" class="panel-collapse collapse"><!-- Cuerpo del panel -->
             <div class="panel-body">

               <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                  <li><a class="list-productos" href="#">Anti-oxidantes de planchas </a></li>
                  <li><a class="list-productos" href="#">Desengrasantes </a></li>
                  <li><a class="list-productos" href="#">Limpiadores </a></li>
                  <li><a class="list-productos" href="#">Relavador </a></li>
               </ul><!--Menu accordion -->

             </div>
           </div>

         </div><!--Panel -->





     <!-- /// Automotriz /// -->

         <div class="panel"><!--Panel -->

           <div class="panel-heading cabezera-panel">
             <h4 class="panel-title">
                <a class="titulos_panel" href="#automotriz" data-toggle="collapse"   data-parent="#accordion">AUTOMOTRIZ</a><!-- titulo -->
             </h4>
           </div>

           <div id="automotriz" class="panel-collapse collapse"><!-- Cuerpo del panel -->
             <div class="panel-body">

               <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                  <li><a class="list-productos" href="#">Acabado natural (Llanta nueva) </a></li>
                  <li><a class="list-productos" href="#">Desengrasante para motores. </a></li>
                  <li><a class="list-productos" href="#">Limpieza óptima de los parabrisas. </a></li>
                  <li><a class="list-productos" href="#">Rejuvenecedor y generador de alto brillo. </a></li>
                  <li><a class="list-productos" href="#">Repele el polvo de las carpas de los remolques </a></li>
                  <li><a class="list-productos" href="#">Shampoo Biodegadables. </a></li>
               </ul><!--Menu accordion -->

             </div>
           </div>

         </div><!--Panel -->

       <!-- /// Hotelera /// -->

         <div class="panel"><!--Panel -->

           <div class="panel-heading cabezera-panel">
             <h4 class="panel-title">
                <a  class="titulos_panel" href="#hotelera" data-toggle="collapse"   data-parent="#accordion">HOTELERA</a><!-- titulo -->
             </h4>
           </div>

           <div id="hotelera" class="panel-collapse collapse"><!-- Cuerpo del panel -->
             <div class="panel-body">

               <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                  <li><a class="list-productos" href="#">Baños </a></li>
                  <li><a class="list-productos" href="#">Cocinas </a></li>
                  <li><a class="list-productos" href="#">Multiusos </a></li>
                  <li><a class="list-productos" href="#">Pisos </a></li>
                  <li><a class="list-productos" href="#">Ropa, manteles, sábanas </a></li>
                  <li><a class="list-productos" href="#">Vidrios </a></li>
               </ul><!--Menu accordion -->

             </div>
           </div>

         </div><!--Panel -->

       <!-- /// MANTENIMIENTO INDUSTRIAL /// -->

         <div class="panel"><!--Panel -->

           <div class="panel-heading cabezera-panel">
             <h4 class="panel-title">
                <a class="titulos_panel" href="#mante-industrial" data-toggle="collapse"   data-parent="#accordion">MANTENIMIENTO INDUSTRIAL</a><!-- titulo -->
             </h4>
           </div>

           <div id="mante-industrial" class="panel-collapse collapse"><!-- Cuerpo del panel -->
             <div class="panel-body">

               <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                  <li><a class="list-productos" href="#">Convertidor, Neutralizador o pasivador de óxidos </a></li>
                  <li><a class="list-productos" href="#">Desengrasantes </a></li>
                  <li><a class="list-productos" href="#">Desincrustantes. </a></li>
                  <li><a class="list-productos" href="#">Desoxidantes. </a></li>
                  <li><a class="list-productos" href="#">Detergentes + Desengrasantes. </a></li>
                  <li><a class="list-productos" href="#">Detergentes Biodegradables. </a></li>
                  <li><a class="list-productos" href="#">Dieléctricos. </a></li>
                  <li><a class="list-productos" href="#">Limpiador de formaletas. </a></li>
                  <li><a class="list-productos" href="#">Limpiador y fosfatizante. </a></li>
                  <li><a class="list-productos" href="#">Removedor de pinturas. </a></li>
               </ul><!--Menu accordion -->

             </div>
           </div>

         </div><!--Panel -->

       <!-- /// MATERIAS PRIMAS /// -->

         <div class="panel"><!--Panel -->

           <div class="panel-heading cabezera-panel">
             <h4 class="panel-title">
                <a  class="titulos_panel" href="#materias_primas" data-toggle="collapse"   data-parent="#accordion">MATERIAS PRIMAS</a><!-- titulo -->
             </h4>
           </div>

           <div id="materias_primas" class="panel-collapse collapse"><!-- Cuerpo del panel -->
             <div class="panel-body">

               <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                  <li><a class="list-productos" href="#">Base concentrada Silicona </a></li>
                  <li><a class="list-productos" href="#">Base concentrado Cera </a></li>
                  <li><a class="list-productos" href="#">Base concentrado Creolina </a></li>
               </ul><!--Menu accordion -->

             </div>
           </div>

         </div><!--Panel -->

       <!-- /// SANIDAD PORTÁTIL /// -->

         <div class="panel"><!--Panel -->

           <div class="panel-heading cabezera-panel">
             <h4 class="panel-title">
                <a  class="titulos_panel" href="#sanidad_portatil" data-toggle="collapse"   data-parent="#accordion">SANIDAD PORTÁTIL</a><!-- titulo -->
             </h4>
           </div>

           <div id="sanidad_portatil" class="panel-collapse collapse"><!-- Cuerpo del panel -->
             <div class="panel-body">

               <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                  <li><a class="list-productos" href="#">Desinfectante concentrado. </a></li>
                  <li><a class="list-productos" href="#">Limpiador especializado. </a></li>
               </ul><!--Menu accordion -->

             </div>
           </div>

         </div><!--Panel -->

       <!-- /// TEXTIL /// -->

         <div class="panel"><!--Panel -->

           <div class="panel-heading cabezera-panel">
             <h4 class="panel-title">
                <a  class="titulos_panel" href="#textil" data-toggle="collapse"   data-parent="#accordion">TEXTIL</a><!-- titulo -->
             </h4>
           </div>

           <div id="textil" class="panel-collapse collapse"><!-- Cuerpo del panel -->
             <div class="panel-body">

               <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                  <li><a class="list-productos" href="#">Desinfectante multiusos. </a></li>
                  <li><a class="list-productos" href="#">Detergente textil. </a></li>
                  <li><a class="list-productos" href="#">Suavizante textil. </a></li>
               </ul><!--Menu accordion -->

             </div>
           </div>

         </div><!--Panel -->

       </div><!--Contenido de los paneles -->
    </div><!-- Contenedor -->
   </div>

               <!-- Deomostracion productos -->
             	 <div class=" col-lg-9 col-md-9 col-sm-9">
             	  	   <div><!-- Contenedor -->

                          <div class="col-lg-12 col-md-12 col-sm-12">
														<div><!-- IMG = Linea Seleccionada -->
														      <img src="<?= BASE_IMG_LINEA_SELEC ;?>img_alimentaria.png" class="img-responsive">
														</div><!-- IMG = Linea Seleccionada -->
                          </div>

                          <div class="col-lg-12 col-md-12 col-sm-12">
                             <div class="cont-productos"><!-- Contenedor -->
                                <div class="row">

                                       <div class=" col-lg-3">
                                           <div class="producto">
                                                Producto CITROXYTRON
                                           </div>
                                       </div>
                                       <div class=" col-lg-3">
                                           <div class="producto">
                                                Producto CITROXYTRON
                                           </div>
                                       </div>
                                       <div class=" col-lg-3">
                                           <div class="producto">
                                                Producto CITROXYTRON
                                           </div>
                                       </div>
                                       <div class=" col-lg-3">
                                           <div class="producto">
                                                Producto CITROXYTRON
                                           </div>
                                       </div>

                                  </div>
                              </div>
                          </div>

             	  	   </div><!-- Contenedor -->
             	  </div>
             </div>
         <!-- /// Section = Info-Productos /// -->




























	  </div>
</div><!-- Cont = Principal -->
