<!--
    Js          => Carpeta Js  => balk_velocidad_slider.js
    Estilos Css => Carpeta Css => balk_linea_porducto_vista.css , balk_estilos_generales.css
    *** Cuando se selecciona una linea de producto se carga esta vista con sus productos
     y descripciones ****
   -->
   <div class="cont-pagina"><!-- Cont = Principal -->
     <div class="row">

       <!-- /// Section = Info-Productos /// -->

       <div class="row"><!-- Barra linea productos -->
         <div class=" col-lg-3 col-md-3 col-sm-3">
          <div class="cont-barra-left"><!-- Contenedor -->
           <div class="panel-group" id="accordion"><!--Contenido de los paneles -->

            <?php
              $i= 1;
              foreach ($this->Categorias as $Categorias)
            {
              $nomcategoria = trim($Categorias['nomcategoria']);
              $idcategoria  = $Categorias['idcategoria'];
              $id           = 'item'.$idcategoria;
            ?>
             <div class="panel"><!--Panel -->
               <div class="panel-heading cabezera-panel">
                 <h4 class="panel-title">
                  <a class="titulos_panel" href="#<?=$id ;?>" data-toggle="collapse"   data-parent="#accordion">
                    <?= $nomcategoria ;?>
                  </a><!-- titulo -->
                </h4>
              </div>
              <?php if ($i==1) :;?>
                <div id="<?=$id ;?>" class="panel-collapse collapse in"><!-- Cuerpo del panel -->
              <?php else :;?>
                <div id="<?=$id ;?>" class="panel-collapse collapse"><!-- Cuerpo del panel -->
               <?php endif;?>

               <div class="panel-body">
                 <ul class="list-unstyled accordion" id="accordion"><!-- Menu accordion-->
                 <?php foreach ($this->SubCategorias as $SubCategorias)
                 {
                    $nomsubcategoria     = $SubCategorias['nomsubcategoria'];
                    $idcategoria_detalle = $SubCategorias['idcategoria'];
                    $idsubcategoria      = $SubCategorias['idsubcategoria'];
                    if ($idcategoria == $idcategoria_detalle){
                  ?>
                     <li><a class="list-productos" href="#"><?=$nomsubcategoria ;?> </a></li>


                  <?php }} ;?>
                </ul><!--Menu accordion -->

              </div>
            </div>

          </div><!--Panel -->
           <?php $i++; } ;?>

        </div><!--Contenido de los paneles -->


      </div><!-- Contenedor -->
    </div>
  </div>


</div>
</div><!-- Cont = Principal -->
