<!--
    Js          => Carpeta Js  => balk_velocidad_slider.js
    Estilos Css => Carpeta Css => balk-linea_productos.css , balk_estilos_generales
    ************* Linea De Productos **************                 -->
    <div class="cont-pgn-linea-product"><!-- cont = Principal -->
     <div class="row">

       <!-- /// Demostracion Linea de Productos /// -->
       <div class="col-lg-12 col-md-12 col-sm-12">
         <div><!-- Contenedor  -->

          <div class="row"><!-- Fila Superior -->
           <div><!-- Contenedor linea_producto_vista -->

             <div class="col-lg-3 col-md-3 col-sm-3">
              <a href="<?= BASE_URL ;?>productos/productos_por_categoria/4">
               <img src="<?= BASE_IMG_PRODUCTOS ;?>alimentaria.jpg" class="img-responsive img-line-product">
             </a>
           </div>

           <div class="col-lg-3 col-md-3 col-sm-3">
             <a href="<?= BASE_URL ;?>productos/productos_por_categoria/1">
              <img src="<?= BASE_IMG_PRODUCTOS ;?>graficas.jpg" class="img-responsive img-line-product" id="4">
            </a>
          </div>

          <div class="col-lg-3 col-md-3 col-sm-3">
            <a href="<?= BASE_URL ;?>productos/productos_por_categoria/2">
             <img src="<?= BASE_IMG_PRODUCTOS ;?>automotriz.jpg" class="img-responsive img-line-product" id="6">
           </a>
         </div>

         <div class="col-lg-3 col-md-3 col-sm-3">
           <a href="<?= BASE_URL ;?>productos/productos_por_categoria/5">
            <img src="<?= BASE_IMG_PRODUCTOS ;?>hotelera.jpg" class="img-responsive img-line-product" id="7">
          </a>
        </div>

      </div><!-- Contenedor -->
    </div><!-- Fila Superior -->

    <div class="row"><!-- Fila Inferior -->
     <div>	<!-- Contenedor -->

       <div class="col-lg-3 col-md-3 col-sm-3">
        <a href="<?= BASE_URL ;?>productos/productos_por_categoria/3">
         <img src="<?= BASE_IMG_PRODUCTOS ;?>mant-industrial.jpg" class="img-responsive img-line-product">
       </a>
     </div>

     <div class="col-lg-3 col-md-3 col-sm-3">
       <a href="<?= BASE_URL ;?>productos/productos_por_categoria/8">
        <img src="<?= BASE_IMG_PRODUCTOS ;?>materias-primas.jpg" class="img-responsive img-line-product">
      </a>
    </div>

    <div class="col-lg-3 col-md-3 col-sm-3">
      <a href="<?= BASE_URL ;?>productos/productos_por_categoria/7">
       <img src="<?= BASE_IMG_PRODUCTOS ;?>sanidad.jpg" class="img-responsive img-line-product">
     </a>
   </div>

   <div class="col-lg-3 col-md-3 col-sm-3">
    <a href="<?= BASE_URL ;?>productos/productos_por_categoria/6">
     <img src="<?= BASE_IMG_PRODUCTOS ;?>textil.jpg" class="img-responsive img-line-product">
   </a>
 </div>

</div><!-- Contenedor -->
</div><!-- Fila Inferior -->


</div><!-- Contenedor  -->
</div>
<!-- /// Demostracion Linea de Productos /// -->

</div>
</div><!-- cont = Principal -->
<br>
<br>
<br>
