          <div class="contenido_interno">
           <div class="col-lg-9 col-md-9 col-sm-9">
             <div><!-- Contenedor -->
              <div class="col-lg-12 col-md-12 col-sm-12">
                <div><!-- IMG = Linea Seleccionada -->
                  <img src="<?= BASE_IMG_LINEA_SELEC.$this->Imagen_Cabecera  ;?>" class="img-responsive">
                </div><!-- IMG = Linea Seleccionada -->
              </div>

              <div class="col-lg-12 col-md-12 col-sm-12">


                <!-- ======( Fila De Productos )====== -->
                <div class="row">

                    <?php
                    foreach ($this->Productos as $Producto)
                    {
                      $nomproducto = $Producto['nomproducto']
                      ?>
                      <div class="col-lg-3 col-md-3 col-sm-3">
                       <div class="producto">
                        <?= $nomproducto ;?>
                      </div>
                    </div>
                    <?php } ;?>

                </div><!-- ======( Fila De Productos )====== -->
              </div>
            </div><!-- Contenedor -->
          </div>
        </div>
