          <div class="contenido_interno">
           <div class="col-lg-9 col-md-9 col-sm-9">
             <div><!-- Contenedor -->
              <div class="col-lg-12 col-md-12 col-sm-12">

                <div><!-- IMG = Linea Seleccionada -->
                  <img src="<?= BASE_IMG_LINEA_SELEC.$this->Imagen_Cabecera  ;?>" class="img-responsive img-linea-seleccionada">
                </div><!-- IMG = Linea Seleccionada -->


              </div>

            <div class="contenido-descripcion">

                <div><!-- Titulo -->
                     <h4 class="titulo_linea_seleccionada"><?=$this->Texto_SubCategoria?></h4>
                </div><!-- Titulo -->

              <div class="col-lg-12 col-md-12 col-sm-12">
                   <div class="cont-presentacion-productos">
                        <!-- ======( Fila De Productos )====== -->
                          <div class="row">
                              <?php
                              foreach ($this->Productos as $Producto)
                              {
                                $nomproducto = $Producto['nomproducto'];
                                $idproducto  = $Producto['idproducto'];
                                ?>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                 <div class="producto" id="<?=$nomproducto ;?>">
                                  <?= $nomproducto ;?>
                                </div>
                              </div>
                              <?php } ;?>

                          </div>
                        <!-- ======( Fila De Productos )====== -->
                   </div>
              </div>

              </div>

            </div><!-- Contenedor -->
          </div>
        </div>
  <br />
  <br />
  <br />
  <br />
