<!--
    Estilos Css => Template => balk-footer.css
          ********* Footer *********       -->

<div ><!-- Cont-principal -->
	   <div class="row" style="padding: 0px;">
       <div class="col-lg-12 col-md-12 col-sm-12" style="padding: 0px;">

       	   <div class="cont-footer"><!-- Contenedor -->
	             <strong>PBX :</strong> ( 2 ) 4881616. <br>
	             <strong>Linea gratuita al cliente :</strong> 01 8000 18 TRON ( 8766 ). <br>
	             <strong>Dirección :</strong> Cll 35 N° 4-31 , Cali - Colombia.
           </div><!-- Contenedor -->

       </div>
	   </div>
</div><!-- Cont-principal -->
