<!--
    Estilos Css => Carpeta Css => balk-contactenos.css , balk_estilos_generales.css
                      *********** Contactanos ***********                       -->
<div class="cont-info-pagina"><!-- Cont = Principal -->
    <div class="row">

       <div class="col-lg-12 col-md-12 col-sm-12">

          <!-- Titulo -->
             <h4 style="color: #c76b38; margin-bottom: 20px;">
                 <strong>Control de calidad</strong>
              </h4>
          <!-- Titulo -->


           <!-- Formulario -->
     <div class ="col-lg-12 col-md-12 col-sm-12">

               <div class="col-lg-6">

                 <form class="form-horizontal" role="form">

                    <!-- Nombre Completo -->
                     <div class="form-group">
                         <div>
                         	   <label for="nombre_completo" class="col-lg-5 control-label "><p class="text-label ">Nombre Completo :</p></label>
                         	   <div class="col-lg-7">
                         	   	  <input type="text" class="form-control " id="nombre_completo">
                         	   	  <div class="msj-validacion" id="msj-validacion-nombre"><!-- Msj Validacion -->
                         	           <span><img class="img-malo" src="<?= BASE_IMG_CONTACTANOS ; ?>malo.png" ></span> Escribe Tu Nombre... !!
                                </div><!-- Msj Validacion -->
                         	   </div>
                         </div>
                     </div>
                    <!-- Nombre Completo -->

                    <!-- Ciudad  -->
                        	<div class="form-group">
                        		  <div>
                        			     <label for="ciudad" class="col-lg-5 control-label "><p class="text-label ">Ciudad  :</p></label>
                        		     	<div class="col-lg-7">
                        				        <input type="text" class="form-control" id="ciudad">
                        		           <div class="msj-validacion" id="msj-validacion-ciudad"><!-- Msj = Validacion -->
                        		  	             <span><img class="img-malo" src="<?= BASE_IMG_CONTACTANOS ;?>malo.png" alt=""></span>Escribe Tu Ciudad... !!
                        		           </div><!-- Msj = Validacion -->
                        			     </div>
                        		  </div>
                        		</div>
                    <!-- Ciudad  -->

                    <!-- País -->
                        	<div class="form-group">
                        		  <div>
                        			     <label for="pais" class="col-lg-5 control-label "><p class="text-label">País :</p></label>
                        		     	<div class="col-lg-7">
                        				        <input type="text" class="form-control" id="pais">
                        				         <div class="msj-validacion" id="msj-validacion-pais"><!-- Msj = Validacion -->
                        		  	             <span><img class="img-malo" src="<?= BASE_IMG_CONTACTANOS ;?>malo.png" alt=""></span>Escribe Tu Pais... !!
                        		           </div><!-- Msj = Validacion -->
                        			     </div>
                        		  </div>
                        		</div>
                    <!-- País -->

                    <!--  Empresa -->
                     <div class="form-group">
                         <div>
                         	   <label for="empresa" class="col-lg-5 control-label "><p class="text-label">Empresa  :</p></label>
                         	   <div class="col-lg-7">
                         	   	  <input type="text" class="form-control" id="empresa">
                         	   	  <div class="msj-validacion" id="msj-validacion-empresa"><!-- Msj = Validacion -->
                         	            <span><img class="img-malo" src="<?= BASE_IMG_CONTACTANOS ;?>malo.png" alt=""></span>Escribe Tu Empresa... !!
                                 </div><!-- Msj = Validacion -->
                         	   </div>
                         </div>
                     </div>
                    <!-- Empresa  -->

                    <!-- Actividad de la empresa  -->
                     <div class="form-group">
                         <div>
                         	   <label for="actividad-empresa" class="col-lg-5 control-label "><p class="text-label">Actividad de la empresa  :</p></label>
                         	   <div class="col-lg-7">
                         	   	  <input type="text" class="form-control" id="actividad-empresa">
                         	   	   <div class="msj-validacion" id="msj-validacion-actividad"><!-- Msj = Validacion -->
                         	            <span><img class="img-malo" src="<?= BASE_IMG_CONTACTANOS ;?>malo.png" alt=""></span>Escribe Tu Actividad... !!
                                 </div><!-- Msj = Validacion -->
                         	   </div>
                         </div>
                     </div>
                    <!--  Actividad de la empresa -->

                    <!-- Cargo  -->
                     <div class="form-group">
                         <div>
                         	   <label for="cargo" class="col-lg-5 control-label "><p class="text-label">Cargo  :</p></label>
                         	   <div class="col-lg-7">
                         	   	  <input type="text" class="form-control" id="cargo">
                         	   	  <div class="msj-validacion" id="msj-validacion-cargo"><!-- Msj = Validacion -->
                         	            <span><img class="img-malo" src="<?= BASE_IMG_CONTACTANOS ;?>malo.png" alt=""></span>Escribe Tu Cargo... !!
                                 </div><!-- Msj = Validacion -->
                         	   </div>
                         </div>
                     </div>
                    <!-- Cargo  -->
                  </form>
               </div>


               <div class="col-lg-6">

                 <form class="form-horizontal" role="form">

                    <!-- E-mail  -->
                     <div class="form-group">
                         <div>
                         	   <label for="email " class="col-lg-5 control-label "><p class="text-label">E-mail  :</p></label>
                         	   <div class="col-lg-7">
                         	   	  <input type="text" class="form-control" id="email">
                         	   	  <div class="msj-validacion" id="msj-validacion-email"><!-- Msj = Validacion -->
                         	            <span><img class="img-malo" src="<?= BASE_IMG_CONTACTANOS ;?>malo.png" alt=""></span>Escribe Tu E-mail... !!
                                 </div><!-- Msj = Validacion -->
                         	   </div>
                         </div>
                     </div>
                    <!-- E-mail  -->

                    <!-- Teléfono  -->
                     <div class="form-group">
                         <div>
                         	   <label for="telefono" class="col-lg-5 control-label "><p class="text-label">Teléfono  :</p></label>
                         	   <div class="col-lg-7">
                         	   	  <input type="text" class="form-control" id="telefono">
                         	   	  <div class="msj-validacion" id="msj-validacion-telefono"><!-- Msj = Validacion -->
                         	            <span><img class="img-malo" src="<?= BASE_IMG_CONTACTANOS ;?>malo.png" alt=""></span>Escribe Tu Teléfono... !!
                                 </div><!-- Msj = Validacion -->
                         	   </div>
                         </div>
                     </div>
                    <!--  Teléfono -->

                    <!-- linea-interes  -->
                     <div class="form-group">
                         <div>
                         	   <label for="linea_alimentaria" class="col-lg-5 control-label "><p class="text-label">Linea de Interes :</p></label>
                         	   <div class="col-lg-7">
                         	   	   <select class="form-control" id="linea_alimentaria">
                         	   	   	    <option> Linea Alimentaria </option>
                         	   	   </select>
                         	   </div>
                         </div>
                     </div>
                    <!-- linea-interes  -->

                    <!--  tipo de mensaje -->
                     <div class="form-group">
                         <div>
                         	   <label for="tipo_mensaje" class="col-lg-5 control-label "><p class="text-label">Tipo de mensaje  :</p></label>
                         	   <div class="col-lg-7">
                         	   	  <select class="form-control" id="tipo_mensaje">
                         	   	  	    <option > Vacio </option>
                         	   	  </select>
                         	   </div>
                         </div>
                     </div>
                    <!--   tipo de mensaje-->

                    <!-- Mensaje  -->
                     <div class="form-group">
                         <div>
                         	   <label for="mensaje" class="col-lg-5 control-label "><p class="text-label">Mensaje  :</p></label>
                         	   <div class="col-lg-7">
                         	   	  <textarea class="form-control" id="mensaje" cols="30" rows="4"></textarea>
                         	   	  <div class="msj-validacion" id="msj-validacion-mensaje"><!-- Msj = Validacion -->
                         	            <span><img class="img-malo" src="<?= BASE_IMG_CONTACTANOS ;?>malo.png" alt=""></span>Escribe Tu Mensaje... !!
                                 </div><!-- Msj = Validacion -->
                         	   </div>
                         </div>
                     </div>
                    <!--Mensaje   -->

			  </form>
	 </div>


                <div class="col-lg-12 col-md-12 col-sm-12">
                    <!-- botones = Enviar-datos -->
                     <div class="cont-btn-datos-enviar">
                         <button type="button" class="btn-enviar-datos" id="btn_enviar_datos">Enviar Datos</button>
                     </div>
                    <!-- botones = Enviar-datos -->
                </div>

			 </div>
	           <!-- Formulario -->


            <!-- Linea alimentaria -->
            <div class ="col-lg-12 col-md-12 col-sm-12 barra_contactos">

                <div class="col-lg-6" style="padding: 0px;"><!-- Contactanos = Left -->
                 <!-- Titulos -->
                 <div class="col-lg-3 col-md-3 col-sm-3" style="width: 250px;  ">
                  <p class="titulo_linea">Línea Alimentaria</p>
                  <p class="titulo_linea"> Línea Artes gráficas</p>
                  <p class="titulo_linea">Línea Automotriz</p>
                  <p class="titulo_linea"> Línea Industrial</p>
                  <p class="titulo_linea"> Línea Institucional</p>
              </div>
              <!-- Titulos -->

              <!-- Puntos -->
              <div class="col-lg-1 col-md-1 col-sm-1" style="width: 30px;">

                  <p class=" Puntos text-left"> : </p>
                  <p class=" Puntos text-left"> : </p>
                  <p class=" Puntos text-left"> : </p>
                  <p class=" Puntos text-left"> : </p>
                  <p class=" Puntos text-left"> : </p>
              </div>
              <!-- Puntos -->

              <!-- Correos -->
              <div class="col-lg-4 col-md-4 col-sm-4">
                 <p style="margin-bottom: -1px;"><a  class="correo_contacto " href="mailto:alimentaria@tecnoaplicadas.com"> alimentaria@tecnoaplicadas.com</a></p>
                 <p style="margin-bottom: -1px;"><a  class="correo_contacto" href="mailto:litotron@tecnoaplicadas.com ">litotron@tecnoaplicadas.com </a></p>
                 <p style="margin-bottom: -1px;"><a  class="correo_contacto  " href="mailto:industrial@tecnoaplicadas.com ">industrial@tecnoaplicadas.com </a></p>
                 <p style="margin-bottom: -1px;"><a  class="correo_contacto  " href="mailto: industrial@tecnoaplicadas.com "> industrial@tecnoaplicadas.com </a></p>
                 <p style="margin-bottom: -1px;"><a  class="correo_contacto  " href="mailto:  industrial@tecnoaplicadas.com ">  industrial@tecnoaplicadas.com </a></p>
             </div>
             <!-- Correos -->


         </div><!-- Contactanos = Left -->


         <div class="col-lg-6" style="padding: 0px;"><!-- Contactanos =right -->
             <!-- Titulos -->
             <div class="col-lg-3 col-md-3 col-sm-3" style="width: 250px; padding: 0px;">
               <p class="titulo_linea"> Línea Materias primas</p>
               <p class="titulo_linea"> Línea Sanidad portátil</p>
               <p class="titulo_linea"> Línea Textil</p>
               <p class="titulo_linea">Línea de Reencauche de llanta</p>
               <p class="titulo_linea"> Atención al cliente</p>
           </div>
           <!-- Titulos -->

           <!-- Puntos -->
           <div class="col-lg-1 col-md-1 col-sm-1" style="width: 30px;">

              <p class=" Puntos text-left"> : </p>
              <p class=" Puntos text-left"> : </p>
              <p class=" Puntos text-left"> : </p>
              <p class=" Puntos text-left"> : </p>
              <p class=" Puntos text-left"> : </p>
          </div>
          <!-- Puntos -->

          <!-- Correos -->
          <div class="col-lg-4 col-md-4 col-sm-4">
           <p style="margin-bottom: -1px;"><a  class="correo_contacto  " href="mailto:materiasprimas@tecnoaplicadas.com "> materiasprimas@tecnoaplicadas.com</a></p>
           <p style="margin-bottom: -1px;"><a  class="correo_contacto " href="mailto:materiasprimas@tecnoaplicadas.com">materiasprimas@tecnoaplicadas.com </a></p>
           <p style="margin-bottom: -1px;"> <a  class="correo_contacto  " href="mailto:industrial@tecnoaplicadas.com ">industrial@tecnoaplicadas.com </a> </p>
           <p style="margin-bottom: -1px;"><a  class="correo_contacto  " href="mailto:materiasprimas@tecnoaplicadas.com">materiasprimas@tecnoaplicadas.com</a></p>
           <p style="margin-bottom: -1px;"><a  class="correo_contacto  " href="mailto:info@tecnoaplicadas.com">info@tecnoaplicadas.com</a></p>
         </div>
     <!-- Correos -->

 </div><!-- Contactanos = right -->

</div>
           <!-- Linea alimentaria -->
       </div>

    </div>
</div><!-- Cont = Principal -->
