<!--
    Estilos Css => Carpeta Css => balk-contactenos.css ,
                                  balk_estilos_generales.css
        *********** Contactanos ***********
    -->
    <div class="cont-info-pagina"><!-- Cont = Principal -->
        <div class="row">

         <div class="col-lg-12 col-md-12 col-sm-12">

          <!-- Titulo -->
          <h4 class="text-left  ">
           <strong class="titulo">Contáctanos</strong>
         </h4>
       <!-- Titulo -->


       <!-- Formulario -->
       <div class ="col-lg-12 col-md-12 col-sm-12 cont-formulario">

         <div class="col-lg-6 col-lg-6 col-md-6 col-sm-6">

           <form class="form-horizontal" role="form">

            <!-- Nombre Completo -->
            <div class="form-group">
               <div>
                   <label for="nombre_completo" class="col-lg-5 control-label "><p class="text-label ">Nombre Completo :</p></label>
                   <div class="col-lg-7">
                    <input type="text" class="form-control " id="nombre_completo">

               </div>
           </div>
       </div>
       <!-- Nombre Completo -->

       <!-- Ciudad  -->
       <div class="form-group">
        <div>
            <label for="ciudad" class="col-lg-5 control-label "><p class="text-label ">Ciudad  :</p></label>
            <div class="col-lg-7">
                <input type="text" class="form-control" id="ciudad">

          </div>
      </div>
  </div>
  <!-- Ciudad  -->


<!-- País -->

<!--  Empresa -->
<div class="form-group">
   <div>
       <label for="empresa" class="col-lg-5 control-label "><p class="text-label">Empresa  :</p></label>
       <div class="col-lg-7">
        <input type="text" class="form-control" id="empresa">

  </div>
</div>
</div>
<!-- Empresa  -->




<!-- Cargo  -->
<div class="form-group">
   <div>
       <label for="cargo" class="col-lg-5 control-label "><p class="text-label">Cargo  :</p></label>
       <div class="col-lg-7">
        <input type="text" class="form-control" id="cargo">

  </div>
</div>
</div>
<!-- Cargo  -->

<!-- Mensaje  -->
<div class="form-group">
   <div>
       <label for="mensaje" class="col-lg-5 control-label "><p class="text-label">Mensaje  :</p></label>
       <div class="col-lg-7">
           <textarea class="form-control" id="mensaje" cols="30" rows="1"></textarea>
       </div>
  </div>
</div>
<!--Mensaje   -->
</form>
</div>


<div class="col-lg-6 col-md-6 col-sm-6">

   <form class="form-horizontal" role="form">

    <!-- E-mail  -->
    <div class="form-group">
       <div>
           <label for="email " class="col-lg-5 control-label "><p class="text-label">E-mail  :</p></label>
           <div class="col-lg-7">
            <input type="text" class="form-control" id="email">

      </div>
  </div>
</div>
<!-- E-mail  -->

<!-- Teléfono  -->
<div class="form-group">
   <div>
       <label for="telefono" class="col-lg-5 control-label "><p class="text-label">Teléfono  :</p></label>
       <div class="col-lg-7">
        <input type="text" class="form-control" id="telefono">

  </div>
</div>
</div>
<!--  Teléfono -->

<!-- linea-interes  -->
<div class="form-group">
   <div>
       <label for="linea_alimentaria" class="col-lg-5 control-label "><p class="text-label">Línea de Interés :</p></label>
       <div class="col-lg-7">
           <select class="form-control" id="linea">
           <option id = "0" > Seleccione... </option>
            <?php foreach ($this->Categorias as $Categorias): ?>
            <?php
                $nomcategoria = $Categorias['nomcategoria'];
                $idcategoria  = $Categorias['idcategoria'];
            ?>
            <option id = "<?=$idcategoria ;?>" > <?= $nomcategoria ;?> </option>
            <?php endforeach ?>

          </select>
      </div>
  </div>
</div>
<!-- linea-interes  -->

<!--  tipo de mensaje -->
<div class="form-group">
   <div>
       <label for="tipo_mensaje" class="col-lg-5 control-label "><p class="text-label">Tipo de mensaje  :</p></label>
       <div class="col-lg-7">
        <select class="form-control" id="tipo_mensaje">
           <option id = "0" > Seleccione... </option>
           <option id="1"> Sugerencia  </option>
           <option id="2"> Comentario  </option>
           <option id="3"> Inquietud   </option>
           <option id="4"> Información </option>
           <option id="5"> Post-Venta  </option>
       </select>
   </div>
</div>
</div>
<!--   tipo de mensaje-->


    <!-- botones = Enviar-datos -->
    <div class="cont-btn-datos-enviar">
       <button type="button" class="btn-enviar-datos" id="btn_enviar_datos">Enviar Datos</button>
   </div>
   <!-- botones = Enviar-datos -->
 </form>
</div>



</div>
<!-- Formulario -->

<!-- Linea alimentaria -->
<div class ="col-lg-12 col-md-12 col-sm-12 barra_contactos">

    <div class="col-lg-6"><!-- Contactanos = Left -->
     <!-- Titulos -->
     <div>
         <p class="titulo_linea">
             Línea Alimentaria:
             <span>
                <a href="mailto:alimentaria@balquimia.com">alimentaria@balquimia.com</a>
             </span>
         </p>
     </div>
     <!-- Titulos -->

</div><!-- Contactanos = Left -->


<div class="col-lg-6" style="padding: 0px;"><!-- Contactanos =right -->
    <!-- Titulos -->
    <div class="col-lg-3 col-md-3 col-sm-3" style="width: 250px; padding: 0px;">
     <p class="titulo_linea"> Otras Lineas</p>
 </div>
 <!-- Titulos -->

 <!-- Puntos -->
 <div class="col-lg-1 col-md-1 col-sm-1" style="width: 30px;">
  <p class=" Puntos text-left"> : </p>
</div>
<!-- Puntos -->

<!-- Correos -->
<div class="col-lg-4 col-md-4 col-sm-4">
   <p style="margin-bottom: -1px;"><a  class="correo_contacto  " href="mailto:materiasprimas@tecnoaplicadas.com "> ventas@balquimia.com</a></p>
</div>
<!-- Correos -->
</div><!-- Contactanos = right -->

</div>
<!-- Linea alimentaria -->
</div>

</div>
</div><!-- Cont = Principal -->
<br>
