<!--
    Js         => Carpeta Js  => balk_velocidad_slider.js
    Estlos Css => Carpeta Css => balk-control_calidad.css , balk_estilos_generales.css
               ************ Control de Calidad *************                       -->
 <div class="cont-info-pagina"><!-- Cont = Pagina -->
      <div class="row">

      	  <div class="col-lg-12 col-md-12 col-sm-12">

      	  	     <!-- /// Text = Control De Calidad /// -->
                <div class="row">
                	   <div class="col-lg-12 col-md-12 col-sm-12">
                	     <h4 class="titulo">Control de calidad</h4>
                	   	   <p class="text-justyfy">
                	   	     Uno de nuestros principal objetivos es la calidad. Trabajamos en nuestros productos
                	   	     para que superen sus objetivos de uso y durabilidad. <br>Para conseguir y garantizar
                	   	     este propósito poseemos y aplicamos lo mejor de la tecnología disponible.
                	   	   </p>
                	   </div>
                </div>
                <!-- /// Text = Control De Calidad /// -->

                <!-- /// Slider /// -->
                <div class="row">
                	  <div class="col-lg-12 col-md-12 col-sm-12">
                	  	   <div><!-- Contenedor -->

			                      <section id="slide-desarrollo--prod" class="carousel slide"><!-- Indicadores -->
			                           <ol class="carousel-indicators">
			                                <li data-target="#slide-desarrollo--prod" data-slide-to="0" class="active"></li>
			                                <li data-target="#slide-desarrollo--prod" data-slide-to="1"></li>
			                                <li data-target="#slide-desarrollo--prod" data-slide-to="2"></li>
			                                <li data-target="#slide-desarrollo--prod" data-slide-to="3"></li>
			                           </ol><!-- Indicadores -->

			                          <div class="carousel-inner"><!-- IMG = Slider -->
			                          	   <div class="item active"><img  src="<?= BASE_IMG_CONTROL_CALIDAD ; ?>slider_1.png" style="width: 100%; height: 250px;"></div>

			                          	   <div class="item"><img src="<?= BASE_IMG_CONTROL_CALIDAD ; ?>slider_2.png" style="width: 100%; height: 250px;"></div>

			                          	   <div class="item"><img src="<?=  BASE_IMG_CONTROL_CALIDAD ; ?>slider_3.png" style="width: 100%; height: 250px;"></div>

			                          	    <div class="item"><img src="<?= BASE_IMG_CONTROL_CALIDAD ; ?>slider_4.png" style="width: 100%; height: 250px;"></div>
			                          </div><!-- IMG = Slider -->

			                          <!-- Flecha ((  <=  ))-->
								                      <a href="#slide-desarrollo--prod" class="left carousel-control" data-slide="prev">
								                      	  <span class="glyphicon glyphicon-chevron-left"></span>
								                      </a>

			                          <!-- Flecha ((  =>  ))-->
								                      <a href="#slide-desarrollo--prod" class="right carousel-control" data-slide="next">
								                      	  <span class="glyphicon glyphicon-chevron-right"></span>
								                      </a>
			                      </section>

                	  	   </div><!-- Contenedor -->
                	  </div>
                </div>
                <!-- /// Slider /// -->

      	  </div>
      </div>
 </div><!-- Cont = Pagina -->


