<!--
    Js          => Carpeta Js  => balk_velocidad_slider.js
    Estilos Css => Carpeta Css => balk_desarrollo_productos , balk_estilos_generales.css
        ********* Desarrollo de Productos **********  -->

<div class="cont-desarrollo-product"><!-- Cont = Principal -->
	    <div class="row">

           <!-- Cuepor = Pag -->
               <div class="col-lg-12 col-md-12 col-sm-12"><!-- cont = ( 1 ) -->

                 <div class="cont-info-slider"><!-- conetedor -->

						        <!-- Text = desarroll productos -->
			                 <div class="row">
			                	    <div class="col-lg-12 col-md-12 col-sm-12">
			                	    	   <h4 class="titulo">Desarrollo de productos</h4>

			                	    	   <p class="text-justyfy">
			                	    	          Contamos con un departamento especializado en investigación y
			                	    	          desarrollo de nuevos productos para los diferentes sectores del
			                	    	          mercado industrial, ofreciendo alta calidad, eficiencia y durabilidad.
			                	    	   </p>
			                	    </div>
			                </div>
						         <!-- Text = desarroll productos -->

                <!-- Slider -->
                  <div class="row">
								        	  <div class="col-lg-12 col-md-12 col-sm-12">
								        	   	   <div class="cont-slider-top">

						                      <section id="slide-desarrollo--prod" class="carousel slide"><!-- Indicadores -->
						                           <ol class="carousel-indicators">
						                                <li data-target="#slide-desarrollo--prod" data-slide-to="0" class="active"></li>
						                                <li data-target="#slide-desarrollo--prod" data-slide-to="1"></li>
						                                <li data-target="#slide-desarrollo--prod" data-slide-to="2"></li>
						                                <li data-target="#slide-desarrollo--prod" data-slide-to="3"></li>
						                           </ol><!-- Indicadores -->

						                          <div class="carousel-inner"><!-- IMG = Slider -->
						                          	   <div class="item active"><img  src="<?= BASE_IMG_DESARROLLO_PRODUCT ; ?>slider_1.png" style="width: 100%; height: 250px;"></div>

						                          	   <div class="item"><img src="<?= BASE_IMG_DESARROLLO_PRODUCT ; ?>slider_2.png" style="width: 100%; height: 250px;"></div>

						                          	   <div class="item"><img src="<?= BASE_IMG_DESARROLLO_PRODUCT ; ?>slider_3.png" style="width: 100%; height: 250px;"></div>

						                          	    <div class="item"><img src="<?= BASE_IMG_DESARROLLO_PRODUCT ; ?>slider_4.png" style="width: 100%; height: 250px;"></div>
						                          </div><!-- IMG = Slider -->

						                          <!-- Flecha ((  <=  ))-->
											                      <a href="#slide-desarrollo--prod" class="left carousel-control" data-slide="prev">
											                      	  <span class="glyphicon glyphicon-chevron-left"></span>
											                      </a>

						                          <!-- Flecha ((  =>  ))-->
											                      <a href="#slide-desarrollo--prod" class="right carousel-control" data-slide="next">
											                      	  <span class="glyphicon glyphicon-chevron-right"></span>
											                      </a>
						                      </section><br>

								        	   	   </div>
								        	  </div>
                  </div>
                <!-- Slider -->
                  </div><!-- conetedor -->

               </div><!-- cont = ( 1 ) -->
           <!-- Cuepor = Pag -->
	    </div>
</div><!-- Cont = Principal -->
<br>
<br>
<br>

