<!--
    Js          => Carpeta Js  => balk_velocidad_slider.js
    Estilos Css => Carpeta Css => balk-linea_productos.css , balk_estilos_generales
               ************* Linea De Productos **************                 -->
<div class="cont-pgn-linea-product"><!-- cont = Principal -->
	    <div class="row">

           <!-- /// Demostracion Linea de Productos /// -->
               <div class="col-lg-12 col-md-12 col-sm-12">
               	   <div><!-- Contenedor  -->

               	   	   <div class="row"><!-- Fila Superior -->
               	   	     <div><!-- Contenedor -->

               	   	        <div class="col-lg-3 col-md-3 col-sm-3">
               	   	             <a href="<?= BASE_URL ;?>Empresa/linea_alimentaria">
               	   	             	   <img src="<?= BASE_IMG_PRODUCTOS ;?>alimentaria.jpg" class="img-responsive img-line-product">
               	   	             </a>
               	   	        </div>

               	   	       	<div class="col-lg-3 col-md-3 col-sm-3">
               	   	       	     <a href="#">
               	   	       	     	   <img src="<?= BASE_IMG_PRODUCTOS ;?>graficas.jpg" class="img-responsive img-line-product">
               	   	       	     </a>
               	   	       	</div>

               	   	       	<div class="col-lg-3 col-md-3 col-sm-3">
               	   	       	     <a href="#">
               	   	       	     	   <img src="<?= BASE_IMG_PRODUCTOS ;?>automotriz.jpg" class="img-responsive img-line-product">
               	   	       	     </a>
               	   	       	</div>

               	   	       	<div class="col-lg-3 col-md-3 col-sm-3">
               	   	       	     <a href="#">
               	   	       	     	   <img src="<?= BASE_IMG_PRODUCTOS ;?>hotelera.jpg" class="img-responsive img-line-product">
               	   	       	     </a>
               	   	       	</div>

               	   	      </div><!-- Contenedor -->
               	   	   </div><!-- Fila Superior -->

               	   	   <div class="row"><!-- Fila Inferior -->
               	   	     <div>	<!-- Contenedor -->

               	   	        <div class="col-lg-3 col-md-3 col-sm-3">
               	   	             <a href="#">
               	   	             	   <img src="<?= BASE_IMG_PRODUCTOS ;?>mant-industrial.jpg" class="img-responsive img-line-product">
               	   	             </a>
               	   	        </div>

               	   	       	<div class="col-lg-3 col-md-3 col-sm-3">
               	   	       	     <a href="#">
               	   	       	     	   <img src="<?= BASE_IMG_PRODUCTOS ;?>materias-primas.jpg" class="img-responsive img-line-product">
               	   	       	     </a>
               	   	       	</div>

               	   	       	<div class="col-lg-3 col-md-3 col-sm-3">
               	   	       	     <a href="#">
               	   	       	     	   <img src="<?= BASE_IMG_PRODUCTOS ;?>sanidad.jpg" class="img-responsive img-line-product">
               	   	       	     </a>
               	   	       	</div>

               	   	       	<div class="col-lg-3 col-md-3 col-sm-3">
               	   	       	     <a href="#">
               	   	       	     	   <img src="<?= BASE_IMG_PRODUCTOS ;?>textil.jpg" class="img-responsive img-line-product">
               	   	       	     </a>
               	   	       	</div>

               	   	     </div><!-- Contenedor -->
               	   	   </div><!-- Fila Inferior -->


               	   </div><!-- Contenedor  -->
               </div>
           <!-- /// Demostracion Linea de Productos /// -->

          <!-- /// Slider /// -->
              <div class="well col-lg-12 col-md-12 col-sm-12">
                  <div>	<!-- Contenedor -->

                  </div><!-- Contenedor -->
              </div>
          <!-- /// Slider /// -->

	    </div>
</div><!-- cont = Principal -->
