<!--
     Js          => Carpeta Js  => balk_velocidad_slider.js
     Estilos Css => Carpeta Css => balk-nuestra_empresa.css , balk_estilos_generales.css
     ********* Nuestra Empresa *********       -->

     <div class="cont-nuestra-empresa"><!-- Cont-Principal -->
     	<div class="row">

     		<!-- /// Cuepo-pgn /// -->
     		<div><!-- contenedor -->
     			<div class="col-lg-12 col-md-12 col-sm-12">

     				<!-- Slider = Izquierdad -->
     				<div class="col-lg-3 col-md-3 col-sm-3">
     					<div><!-- slider -->
						        <section id="slide-left"class="carousel slide">
                <ol class="carousel-indicators">
                  <li data-target="#slide-left" data-slide-to="0" class="active"></li>
                  <li data-target="#slide-left" data-slide-to="1"></li>
                  <li data-target="#slide-left" data-slide-to="2"></li>
                  <li data-target="#slide-left" data-slide-to="3"></li>
                  <li data-target="#slide-left" data-slide-to="4"></li>
                  <li data-target="#slide-left" data-slide-to="5"></li>
                  <li data-target="#slide-left" data-slide-to="6"></li>
                  <li data-target="#slide-left" data-slide-to="7"></li>
                  <li data-target="#slide-left" data-slide-to="8"></li>
                </ol>

                <div class="carousel-inner">
                   <div class="item active"><img src= "<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider_1.gif" style="width:  100%; height: 450px;"></div>

                   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider_2.gif" style="width:  100%; height: 450px;"></div>

                   <div class="item"> <img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider_3.gif" style="width:  100%; height: 450px;"></div>

                   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider_4.gif" style="width:  100%; height: 450px;"></div>

                   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider_5.gif" style="width:  100%; height: 450px;"></div>

                   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider_6.gif" style="width:  100%; height: 450px;"></div>

                   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider_7.gif" style="width:  100%; height: 450px;"></div>

                   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider_8.gif" style="width:  100%; height: 450px;"></div>

                   <div class="item">  <img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider_9.gif" style="width:  100%; height: 450px;"></div>
                </div>

                <a href="#slide-left" class="left carousel-control" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>

                 <a href="#slide-left" class="right carousel-control" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
						        </section>

     					</div><!-- slider -->
     				</div><!-- slider -->

     			<!-- Slider = Izquierdad -->



     			<div class="col-lg-9 col-md-9 col-sm-9"><!-- Nuestra Empresa -->

        <!-- Slider = Top -->
		        <div class="row">
		        	  <div class="col-lg-12 col-md-12 col-sm-12">
		        	   	   <div class="cont-slider-top">
                      <section id="topSlide" class="carousel slide"><!-- Indicadores -->
                           <ol class="carousel-indicators">
                                <li data-target="#topSlide" data-slide-to="0" class="active"></li>
                                <li data-target="#topSlide" data-slide-to="1"></li>
                                <li data-target="#topSlide" data-slide-to="2"></li>
                           </ol><!-- Indicadores -->

                          <div class="carousel-inner"><!-- IMG = Slider -->
                          	   <div class="item active"><img  src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider2_1.png" style="width: 100%; height: 250px;"></div>

                          	   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider2_2.png" style="width: 100%; height: 250px;"></div>

                          	   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider2_3.png" style="width: 100%; height: 250px;"></div>
                          </div><!-- IMG = Slider -->

                          <!-- Flecha ((  <=  ))-->
					                      <a href="#topSlide" class="left carousel-control" data-slide="prev">
					                      	  <span class="glyphicon glyphicon-chevron-left"></span>
					                      </a>

                          <!-- Flecha ((  =>  ))-->
					                      <a href="#topSlide" class="right carousel-control" data-slide="next">
					                      	  <span class="glyphicon glyphicon-chevron-right"></span>
					                      </a>
                      </section><br>
		        	   	   </div>
		        	  </div>
		        </div>
       <!-- Slider -->

      <!-- Text = Nuestra -empesa -->
     				<div class="row">
     					<div class="col-lg-12 col-md-12 col-sm-12">
					     						<h4 class="titulo"><strong>Nuestra Empresa</strong></h4> <!-- Titulo -->

					     						<p class="text-justyfy">
					     							Balquimias S.A.S es una empresa colombiana con más de dos décadas de experiencia en el
					     							mercado industrial. Desarrollamos y fabricamos productos de la más alta calidad, con el proposito
					     							de brindar las mejores soluciones en limpieza, desinfección y mantenimiento industrial, en sectores
					     							como el  alimentario, artes gráficas, industrial, sanidad portátil, materias primas para los
					     							industriales del aseo y del reencauche. <br><br>
					     							Nuestra misión es solucionar los requerimientos específicos de cada sector, ofreciéndoles los
					     							productos más adecuados y especializados, elaborados de acuerdo a las necesidades específicas
					     							de cada sector. <br>
					     							Detergentes, Desinfectantes, Desengrasantes, Desoxidantes, Dieléctricos, Desincrustantes,
					     							removedores de tintas, Desmoldantes, Despercudidores, Abrillantadores y Ceras de varios
					     							tipos, son algunos de los productos que usted puede encontrar en Balquimias S.A.S
					     						</p>
     					</div>
     				</div>
      <!-- Text = Nuestra -empesa -->

     			</div> <!-- Nuestra Empresa -->



     		</div>
     	</div><!-- contenedor -->
     	<!-- /// Cuepo-pgn /// -->


     </div>
</div><!-- Cont-Principal -->
