<!--
     Estilos Css => Carpeta Css => balk-nuestros_clientes.css , balk_estilos_generales.css
                 ************* Nuesgtros Clientes ************                         -->
<div class="cont-info-pagina"><!-- Cont = Principal -->
	    <div class="row">

          <div class="col-lg-12 col-md-12 col-sm-12">


              	   <h4 class="titulo">Nuestros Clientes</h4>
    				          <!-- IMG = Nuestros Clientes -->
    				             <div class="col-lg-4 col-md-4 col-sm-4">
    				                  <img src="<?=  BASE_IMG_CLIENTES ;?>clientes.jpg"   >
                              <br>
                              <br>
                              <br>
                              <br>
    				             </div>
<br>


                      <!-- Text = Nuestros Clientes -->

          </div>


	    </div>
</div><!-- Cont = Principal -->
<br>
<br>
<br>

