<!--
     Estilos Css => Carpeta Css => balk-nuestros_clientes.css , balk_estilos_generales.css
                 ************* Nuesgtros Clientes ************                         -->
<div class="cont-info-pagina"><!-- Cont = Principal -->
	    <div class="row">

          <div class="col-lg-12 col-md-12 col-sm-12">
              <div><!-- Contenedor -->

              	   <h4 class="titulo">Nuestros Clientes</h4>
								          <!-- IMG = Nuestros Clientes -->
								             <div class="col-lg-4 col-md-4 col-sm-4">
								                  <img src="<?=  BASE_IMG_CLIENTES ;?>clientes.jpg"  class="img-responsive">
								             </div>
								          <!-- IMG = Nuestros Clientes -->


                  <!-- Text = Nuestros Clientes -->
								              <div class="col-lg-8 col-md-8 col-sm-8">
                          <p>
																												Nuestros clientes son la mejor carta de presentación y muestra de
																												nuestro profesionalismo. <br>
																												Nos enorgullece saber que la confianza que han depositado en nosotros
																												es el resultado de nuestro trabajo y procesos de mejoramiento contínuo
																												que nos permiten brindar productos elaborados con los mejores estándares
																												de calidad para su satisfacción.
                           </p>
								              </div>
                  <!-- Text = Nuestros Clientes -->
              </div><!-- Contenedor -->
          </div>

           <div class="col-lg-12 col-md-12 col-sm-12"><!-- IMG = Clienets- Bottom -->
           	   <div class="cont-img-bottom"><!-- Contenedor -->
           	   	     <img src="<?=  BASE_IMG_CLIENTES ;?>clientes2.jpg" class="img-responsive img-nuestros_procesos">
           	   </div><!-- Contenedor -->
           </div><!-- IMG = Clienets- Bottom -->
	    </div>
</div><!-- Cont = Principal -->
<br>
<br>
<br>
<br>
<br>
