<!--
     Estilos Css => Carpeta Css => balk-nuestro_servicios.css , balk_estilos_generales.css
                     *********** Nuestros Servicios ***********                        -->
<div class="cont-info-pagina"><!-- Cont = Principal -->
   <div class="row">

      	  <div class="col-lg-12 col-md-12 col-sm-12">

      	  	     <!-- /// Text = Nuestro servicios /// -->
                <div class="row">
                	   <div class="col-lg-12 col-md-12 col-sm-12">
                	     <h4 class="titulo">Nuestros Servicios</h4>
                	   	   <p class="text-justyfy">
                	   	     En Balquimias S.A.S contamos con un equipo de profesionales
                	   	     idóneos, orientados a la  asesoría técnica de postventa, que garantizan
                	   	     la óptima implementación y el manejo eficiente de nuestros productos.</p>
                	   </div>
                </div>
                <!-- /// Text = Nuestro servicios /// -->

                <!-- /// IMG = Nuestro servicios /// -->
                <div class="row">
                	  <div class="col-lg-12 col-md-12 col-sm-12">
                	  	   <div><!-- Contenedor -->
                             <img src="<?= BASE_IMG_SERVICIOS ;?>servicios.png" class="img-responsive img-servicios">
                	  	   </div><!-- Contenedor -->
                	  </div>
                </div>
                <!-- /// IMG = Nuestro servicios /// -->
      	  </div>
   </div>
</div><!-- Cont = Principal -->
<br>
<br>
<br>
