<!--
     Js          => Carpeta Js  => balk_velocidad_slider.js
     Estilos Css => Carpeta Css => balk-inex.css
     ******** Index = pag-principal **********   -->

<div class="contenedor-index"><!-- cont = Principal -->
	   <div class="row">

    <!-- /// Slider /// -->
       <div ><!-- Cont-slider -->
       	  <div class="col-lg-12 col-md-12 col-sm-12">
       	   	   <div class="cont-slider">
                   <section id="topSlide" class="carousel slide"><!-- Indicadores -->
                        <ol class="carousel-indicators">
                             <li data-target="#topSlide" data-slide-to="0" class="active"></li>
                             <li data-target="#topSlide" data-slide-to="1"></li>
                             <li data-target="#topSlide" data-slide-to="2"></li>
                        </ol><!-- Indicadores -->

                       <div class="carousel-inner"><!-- IMG = Slider -->
                       	   <div class="item active"><img  src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider2_1.png" style="width: 100%; height: 400px;"></div>

                       	   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider2_2.png" style="width: 100%; height: 400px;"></div>

                       	   <div class="item"><img src="<?= BASE_IMG_SLIDER_NUESTRA_EMPRESA ; ?>slider2_3.png" style="width: 100%; height:400px;"></div>
                       </div><!-- IMG = Slider -->

                       <!-- Flecha ((  <=  ))-->
		                      <a href="#topSlide" class="left carousel-control" data-slide="prev">
		                      	  <span class="glyphicon glyphicon-chevron-left"></span>
		                      </a>

                       <!-- Flecha ((  =>  ))-->
		                      <a href="#topSlide" class="right carousel-control" data-slide="next">
		                      	  <span class="glyphicon glyphicon-chevron-right"></span>
		                      </a>
                   </section><br>
       	   	   </div>
       	  </div>
       </div><!-- Cont-slider -->
    <!-- /// Slider /// -->

	   </div>
</div><!-- cont = Principal -->
<br>
